{% set name = "punx" %}
{% set version = "0.3.4rc2" %}
{% set sha256 = "62c9745cc6c262fdf7ef863ae9086b930b9c4570161455c0d3ff0c2aa50f0598" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - punx=punx.main:main
  # per https://github.com/pypa/setuptools_scm/issues/357#issuecomment-846476165
  # SETUPTOOLS_SCM_PRETEND_VERSION="$(python3 setup.py --version)" pip install .
  script: SETUPTOOLS_SCM_DEBUG=1 SETUPTOOLS_SCM_PRETEND_VERSION="$(python3 setup.py --version)" {{ PYTHON }} -m pip install . -vv
  # skip: true  # [py<38 and py>310]
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - conda-verify
    - pip
    - python >=3.8
    - setuptools-scm >=6.2
  run:
    - h5py >=3
    - hdf5plugin
    - lxml
    - numpy
    - python >=3.8
    - pip
    - pyqt =5
    - pyRestTable
    - requests
    - sip

test:
  imports:
    - punx
  commands:
    - punx --help

about:
  home: https://prjemian.github.io/punx/
  license: CC-BY-4.0
  license_file: punx/LICENSE.txt
  summary: Python Utilities for NeXus
  dev_url: https://github.com/prjemian/punx
  doc_url: https://prjemian.github.io/punx/

extra:
  recipe-maintainers:
    - conda-forge/event-model
    - kbeeperez
    - mrakitin
    - prjemian
